#!/usr/bin/env python3
"""Verify the independently frozen v2 holdout without invoking an Agent model.

The frozen JSONL is deliberately not generated by this script. Gold SQL goes
through the same QueryService boundary used by the production Agent.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import duckdb

from trust_agent.eval.tasks import load_cases
from trust_agent.sql import QueryService

ROOT = Path(__file__).resolve().parents[1]
SUITE = ROOT / "evals/frozen_heldout_v2.jsonl"
DATABASE = ROOT / "data/nyc_taxi.duckdb"
SOURCE_MANIFEST = ROOT / "data/source_manifest.json"
AMBIGUITIES = ROOT / "evals/known_ambiguities_v1.json"
SNAPSHOT = "nyc-tlc-yellow-2025-01-02-v1"
SUITE_SHA256 = "5f3c4ccf6493066362381e0904ef14bc40975e40871d551102a827e6a027527c"
SOURCE_MANIFEST_SHA256 = "48fbd0a206fe5f9a9b3fe756f1d739dd805b01985526e958c9e5a4897620225d"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verify() -> tuple[int, int]:
    if digest(SUITE) != SUITE_SHA256:
        raise ValueError("v2 holdout changed after freeze; create a new version instead")
    if digest(SOURCE_MANIFEST) != SOURCE_MANIFEST_SHA256:
        raise ValueError("source manifest changed after v2 holdout freeze")
    cases = load_cases(SUITE)
    if len(cases) != 20 or [case.id for case in cases] != [f"H{n}" for n in range(201, 221)]:
        raise ValueError("expected exactly H201–H220 in the frozen order")
    if len({case.question for case in cases}) != len(cases):
        raise ValueError("duplicate v2 question")
    raw = [json.loads(line) for line in SUITE.read_text(encoding="utf-8").splitlines()]
    if any(item.get("split") != "heldout_v2" or item.get("dataset_snapshot") != SNAPSHOT
           for item in raw):
        raise ValueError("wrong split or dataset snapshot in v2 holdout")
    numeric = [case for case in cases if case.is_numeric]
    behavior = [case for case in cases if not case.is_numeric]
    if len(numeric) != 12 or len(behavior) != 8:
        raise ValueError("expected 12 numeric and 8 behavioral cases")
    if any(not case.expected_rows for case in numeric):
        raise ValueError("numeric gold cannot be an empty result")

    with duckdb.connect(str(DATABASE), read_only=True,
                        config={"enable_external_access": "false"}) as connection:
        metadata = dict(connection.execute("SELECT key, value FROM dataset_metadata").fetchall())
    if metadata.get("snapshot") != SNAPSHOT:
        raise ValueError("database snapshot does not match v2 holdout")
    if metadata.get("source_manifest_sha256") != SOURCE_MANIFEST_SHA256:
        raise ValueError("database source manifest does not match v2 holdout")

    service = QueryService(DATABASE, ("trips", "zones"))
    for case in numeric:
        assert case.gold_sql is not None
        result = service.query(case.gold_sql, timeout_s=30)
        if result["truncated"] or result["row_count"] != len(result["rows"]):
            raise ValueError(f"{case.id}: gold query result was truncated")
        if result["rows"] != case.expected_rows:
            raise ValueError(f"{case.id}: QueryService result differs from frozen gold")

    errata = json.loads(AMBIGUITIES.read_text(encoding="utf-8"))
    if (errata.get("version") != 1 or errata.get("dataset_snapshot") != SNAPSHOT
            or errata.get("historical_assets_immutable") is not True):
        raise ValueError("ambiguity sidecar metadata differs from the reviewed version")
    entries = errata.get("ambiguities")
    if not isinstance(entries, list) or [entry.get("case_id") for entry in entries] != ["E020"]:
        raise ValueError("v1 ambiguity sidecar must contain exactly E020")
    for entry in entries:
        if entry.get("decision") != "needs_review" or not entry.get("rationale"):
            raise ValueError("ambiguity sidecar requires a review decision and rationale")
        alternative = service.query(entry["alternative_sql"], timeout_s=30)
        if (alternative["truncated"] or alternative["row_count"] != len(alternative["rows"])
                or alternative["rows"] != entry["alternative_expected_rows"]):
            raise ValueError(f"{entry['case_id']}: alternative SQL differs from sidecar result")
    return len(numeric), len(behavior)


def main() -> int:
    numeric, behavior = verify()
    print(f"v2 holdout SHA-256: {SUITE_SHA256}")
    print(f"verified {numeric}/{numeric} numeric gold results through production QueryService")
    print(f"{behavior} behavioral rubrics require human review; no Agent model was run")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
